services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
    command: >
        bash -c "composer install && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data:
